#!/usr/bin/env sh
# Enforce the project's commit message convention: one Conventional Commits
# line, no body, no footer.
#
# Invoked by .githooks/commit-msg (contributors) and .beads/hooks/commit-msg
# (maintainers running the beads issue tracker).
#
# Usage: check-commit-msg.sh <path-to-commit-message-file>
set -eu

msg_file=$1
root=$(git rev-parse --show-toplevel)

# Merge and revert messages are generated by git, not written by the author, and
# carry a body it does not control. Detect them from repository state — the
# message text itself is author-controlled and would be trivial to imitate.
git_dir=$(git rev-parse --git-dir)
if [ -e "$git_dir/MERGE_HEAD" ] || [ -e "$git_dir/REVERT_HEAD" ]; then
    exit 0
fi

# Drop git's comment lines, then any leading blank lines.
content=$(sed -e '/^#/d' "$msg_file" | sed -e '/./,$!d')
subject=$(printf '%s\n' "$content" | head -1)

# `git commit --fixup`/`--squash` produce these prefixes. Rebase autosquash
# removes the commits before they can reach a pull request.
case "$subject" in
    fixup!\ *|squash!\ *) exit 0 ;;
esac

"$root/scripts/check-commit-subject.sh" "$subject" || exit 1

body=$(printf '%s\n' "$content" | tail -n +2 | sed -e '/^[[:space:]]*$/d')
if [ -n "$body" ]; then
    cat >&2 <<EOF
Commit message has a body. This project uses single-line commit messages only:

$body

Put the detail in the pull request description instead.
EOF
    exit 1
fi
